services:
  postgres:
    image: postgres:15
    container_name: bamboo_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

